dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g gulp
  - npm install
script:
  - npm run lint
  - npm run tsc
  - gulp build
  - npm run test:once
